version: 2
updates:

# Maintain dependencies for GitHub Actions
- package-ecosystem: "github-actions"
  directories:
    - "/"
    - "/.github/actions/*/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 12
  labels: ["component/dependencies"]

# Maintain dependencies for npm
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 12
  labels: ["component/dependencies"]
  ignore:
  - # Needs to be updated along with NodeJS version.
    dependency-name: "@types/node"
    update-types: [version-update:semver-major]
  - # node-fetch 3+ requires ECMAScript modules; we still have issues with them.
    dependency-name: "node-fetch"
    versions: [">2"]
  - # This needs to be done in lockstep with node-fetch.
    dependency-name: "@types/node-fetch"
    versions: [">2"]
  - # We don't utilize @rancher/shell in a meaningful way. It is safe to
    # ignore until we arrive a solution that uses it.
    dependency-name: "@rancher/shell"
    versions: [">0.1"]

# Maintain dependencies for Golang
- package-ecosystem: "gomod"
  directories:
  - "/src/go/*"
  - "/src/go/**/*"
  - "/scripts"
  schedule:
    interval: "daily"
  cooldown:
    default-days: 7
  open-pull-requests-limit: 12
  labels: ["component/dependencies"]
  groups:
    golang-x:
      patterns: ["golang.org/x/*"]
    k8s:
      patterns: ["k8s.io/*"]
