version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["component/dependencies"]

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["component/dependencies"]
    ignore:
      - # Needs to be updated along with NodeJS version.
        dependency-name: "@types/node"
        versions: [ ">16" ]
      - # Blocked by nuxt; this also blocks vue-template-compiler.
        dependency-name: "vue"
        versions: [ ">2.6" ]
      - # Webpack 5 requires Nuxt 3. https://github.com/nuxt/nuxt.js/issues/8252
        dependency-name: "webpack"
        versions: [ ">4" ]
      - # node-fetch 3+ requires ECMAScript modules, but Electron doesn't
        # support that. See https://github.com/electron/electron/issues/21457
        dependency-name: "node-fetch"
        versions: [ ">2" ]
      - # This needs to be done in lockstep with node-fetch.
        dependency-name: "@types/node-fetch"
        versions: [ ">2" ]

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/pkg/rancher-desktop/go/docker-credential-none"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/pkg/rancher-desktop/go/mock-wsl"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/pkg/rancher-desktop/go/nerdctl-stub"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/pkg/rancher-desktop/go/rdctl"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/pkg/rancher-desktop/go/vtunnel"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]

  - package-ecosystem: "gomod"
    directory: "/pkg/rancher-desktop/go/wsl-helper"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 1
    labels: ["component/dependencies"]
    reviewers: [ "Nino-K" ]
