name: e2e tests on Linux

on:
  workflow_dispatch:
  push:
    branches-ignore:
    - 'dependabot/**'
  pull_request: {}

jobs:
  check_paths:
    uses: ./.github/workflows/paths-ignore.yaml
  e2e-tests:
    needs: check_paths
    if: needs.check_paths.outputs.should_run == 'true'
    timeout-minutes: 150
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      # For compatibility with runners without yarn, we need to install node
      # once, install yarn, then install node again to get caching.
      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'
      - run: npm install --global yarn
      - uses: actions/setup-node@v4
        with:
          node-version: '18.16.x'
          cache: yarn
      - uses: actions/setup-go@v5
        with:
          go-version: '^1.21'
          cache-dependency-path: src/go/**/go.sum
      # For now, we don't need to `pip install setuptools` because we're not on
      # Python 3.12; we will need that later, however.
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Disable admin-access before start up
        run: |
          mkdir -p $HOME/.config/rancher-desktop
          cat <<EOF > $HOME/.config/rancher-desktop/settings.json
            {
              "version": 5,
              "application": {
                "adminAccess": false
              }
            }
          EOF
      - name: Enable kvm access
        run: sudo chmod a+rwx /dev/kvm
      - name: Run e2e Tests
        continue-on-error: false
        run: >-
          xvfb-run --auto-servernum --server-args='-screen 0 1280x960x24'
          yarn test:e2e
        env:
          RD_DEBUG_ENABLED: '1'
          CI: true
        timeout-minutes: 150
      - name: Upload failure reports
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failure-reports.zip
          path: ./e2e/reports/*
      - name: Clean up test environment
        run: |
          rm -f $HOME/.config/rancher-desktop.defaults.json
          rm -f $HOME/.config/rancher-desktop.locked.json
        if: always()
