# This workflow builds the Rancher Desktop Extensions Host APIs testing image
# and publishes it.

name: RDX Host APIs Testing image
on:
  push:
    branches: [ main ]
    paths: [ 'bats/tests/extensions/testdata/**' ]
  workflow_dispatch: {}
permissions:
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        persist-credentials: false
    - uses: docker/setup-qemu-action@4574d27a4764455b42196d70a065bc6853246a25 # v3.4.0
    - uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
    - uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5.6.1
      id: meta
      with:
        images: |
          ghcr.io/${{ github.repository }}/rdx-host-api-test
        tags: type=raw,value=latest,enable={{ is_default_branch }}
    - uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}
    - uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6.15.0
      with:
        build-args: variant=host-apis
        context: bats/tests/extensions/testdata
        platforms: |
          linux/amd64
          linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
