name: Generate Upgrade Test Data
on:
  workflow_dispatch: {}
permissions:
  contents: read
jobs:
  build:
    strategy:
      matrix:
        include:
        - platform: mac
          arch: x86_64
          runs-on: macos-15-intel
        - platform: mac
          arch: aarch64
          runs-on: macos-latest
        - platform: win
          runs-on: windows-latest
    runs-on: ${{ matrix.runs-on }}
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
        # Needed to run `git describe` to get full version info
        fetch-depth: 0
    - uses: ./.github/actions/yarn-install
    - run: yarn build
    - run: yarn package
    - name: Upload Windows installer
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: Rancher Desktop Setup.msi
        path: dist/Rancher.Desktop*.msi
        if-no-files-found: error
    - if: runner.os == 'Windows'
      run: cat dist/electron-builder.yaml
    - name: Upload Windows build information
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      with:
        name: build-info.yml
        path: dist/electron-builder.yaml
        if-no-files-found: error
    - name: Upload macOS archive
      uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
      if: matrix.platform == 'mac'
      with:
        name: Rancher Desktop-mac.${{ matrix.arch }}.zip
        path: dist/Rancher Desktop*.zip
        if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        persist-credentials: false
    - uses: ./.github/actions/yarn-install
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      with:
        ref: gh-pages
        path: pages
        persist-credentials: true
    - name: Download installer (msi)
      id: msi
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: Rancher Desktop Setup.msi
        path: RD_SETUP_MSI
    - name: Download mac x86_64 archive
      id: mac_x86_64
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: Rancher Desktop-mac.x86_64.zip
        path: MACX86_ZIP
    - name: Download mac aarch64 archive
      id: mac_aarch64
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: Rancher Desktop-mac.aarch64.zip
        path: MACARM_ZIP
    - name: Download build information
      id: info
      uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6.0.0
      with:
        name: build-info.yml
        path: RD_BUILD_INFO
    - run: node scripts/ts-wrapper.js scripts/populate-update-server.ts
      env:
        RD_SETUP_MSI: ${{ steps.msi.outputs.download-path }}
        RD_MACX86_ZIP: ${{ steps.mac_x86_64.outputs.download-path }}
        RD_MACARM_ZIP: ${{ steps.mac_aarch64.outputs.download-path }}
        RD_BUILD_INFO: ${{ steps.info.outputs.download-path }}
        RD_OUTPUT_DIR: ${{ github.workspace }}/pages
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_ACTOR: ${{ github.actor }}
